version: '2'

services:
  gunicorn:
    build: ./src
    volumes:
      - ./message_store:/opt/teabag/message_store

  nginx:
    restart: always
    build: ./deployment/nginx
    ports:
      - 80:5002
    depends_on:
      - gunicorn
