version: '3'

services:
  gunicorn:
    build: .

  nginx:
    restart: always
    build:
      context: ./deployment
      dockerfile: Dockerfile.nginx
    ports:
      - 5000:5002
    depends_on:
      - gunicorn
